apiVersion: v1
kind: Service
metadata:
  name: cssindex-cluster1
spec:
  ports:
    - name: ccsssl
      protocol: TCP
      port: 8199
      targetPort: 8199
  selector:
    app: cssindex-cluster1
  type: ClusterIP
  sessionAffinity: ClientIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cssindex-cluster1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cssindex-cluster1
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: NotIn
                  values:
                  - cssindex-cluster1
              topologyKey: "kubernetes.io/hostname"
      containers:
      - image: <REGISTRY>/css:latest
        imagePullPolicy: Always
        name: cssindex-cluster1
        ports:
        - containerPort: 8199
          name: cssssl
        readinessProbe:
          tcpSocket:
            port: 8199
          initialDelaySeconds: 5
          periodSeconds: 2
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumeMounts:
          - mountPath: /CSSIndex1_OS1
            name: cpe-index-pvc
            subPath: CSSIndexArea1_OS1
          - name: ecmcfgstore-pvc
            mountPath: "/opt/IBM/ContentSearchServices/CSS_Server/log"
            subPath: css/cssindex_logs
          - name: ecmcfgstore-pvc
            mountPath: "/opt/IBM/ContentSearchServices/CSS_Server/data"
            subPath: css/cssindex_data
          - name: ecmcfgstore-pvc
            mountPath: "/opt/IBM/ContentSearchServices/CSS_Server/temp"
            subPath: css/cssindex_temp
      volumes:
        - name: ecmcfgstore-pvc
          persistentVolumeClaim:
            claimName: ecmcfgstore
        - name: cpe-storagearea-pvc
          persistentVolumeClaim:
            claimName: ecmfilestore
        - name: cpe-index-pvc
          persistentVolumeClaim:
            claimName: ecmindexstore
